server:
    port: 8080
    address: 0.0.0.0

spring:
    application:
        name: springBoot_blog
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: asd1234
        url: jdbc:mysql://127.0.0.1/springBoot_blog
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL8Dialect
              format_sql: true
          show_sql: true


