
# 서버 포트 설정
server:
    port: 8080
    address: 0.0.0.0

spring:
    application:
        name: springBoot_blog
    
    # DataBase 연동 설정
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: asd1234
        url: jdbc:mysql://127.0.0.1/springBoot_blog
        username: root

    # Spring Data JPA 설정
    jpa:
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL8Dialect
              format_sql: true
          show_sql: true
    
    # 애플리케이션을 시작하고 디자인 수정 후 새로고침을 하더라도
    # 수정 전의 페이지만 나오는 것을 확인 할 수 있는데 
    # 이를 보완하기 위해 해당 캐싱의 속성을 설정 (배포 시 true 설정)
    thymeleaf:
        cache: false

    # 리소스 찾을 위치 변경 가능
    # 모든 자원을 /resources/** 로 재배치 하고 싶다면 아래의 설정을 추가해주면 된다.
    #mvc:
        #static-path-pattern: /resources/**